# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048


name: AngularOrion - Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - master
    paths-ignore:
      - API/**
      - Blazor/**
      - Web/**
      - Tests/**
  
jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Build with dotnet
      run: dotnet build Angular --configuration Release

    - name: npm install & build
      run: |
        cd Angular
        npm ci
        npm build
        
    - name: dotnet publish
      run: dotnet publish Angular -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: AngularOrion
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F6A1046A34544FD0A5ED83D6159CBFC7 }}
        package: ${{env.DOTNET_ROOT}}/myapp